# ┏━━━━━━━━━━━━━━━ General paths ━━━━━━━━━━━━━━━━┓
paths:
  data_root:        "Data"                          # Where all raw providers live
  chronos_subdir:   "Chronos"
  bolt_subdir:      "Bolt"
  tirex_subdir:     "Tirex"
  output_root:      "Output"                        # Checkpoints / TensorBoard runs


# ┏━━━━━━━━━━ Which dataset to train on ━━━━━━━━━┓
dataset:
  source:  "Chronos"                                # Chronos | Bolt | Tirex
  type:    "equities"                               # Equities | Crypto
  symbol:  "SPY"                                    # e.g. SPY or BTC


# ┏━━━━━━━━ Data-split & sequence shape ━━━━━━━━━┓
splits:
  train: 0.70                                       # Adds up to 1: train + val + test
  val:   0.15
  test:  0.15

sequence_length: 90                                 # L = 90 time-steps as model context
future_offset:   7                                  # Horizon used when generating labels

# ┏━━━━━━━━━━━━━━ Training Mode ━━━━━━━━━━━━━━━┓
training_mode:
  # ┏━━━━━━━━━━━━━━ Optuna ━━━━━━━━━━━━━━━┓
  cross_validation: false                           # Training with (true) or without (false) Cross-Validation (including Optuna)
  cross_val_props:  0.40                             # Proportion for the Cross-Validation within the Training Split
  optuna_task:      "DN"                                 # Only for Optuna Optimization

  loss_function:    "cross_entropy"                              # bce | cross_entropy | focal
  focal_gamma:      3.5852105111000805
  focal_alpha:      0.18850587399901642
  num_classes:      1                                   # 1 (bce) | 2 (cross_entropy, focal)
  padding:          true                                     # For 1D-CNN

  
# ┏━━━━━━━━━━━━━━ Model – UP task ━━━━━━━━━━━━━━━┓
model_up:
  # ┏━━━━━━━━━━━━━━ CNN ━━━━━━━━━━━━━━━┓
  cnn_embed_dim: [64]
  cnn_kernel:    [4]
  cnn_stride:    [2]
  p_pos_drop:    0.1490361359420283                # Positional-dropout

  # ┏━━━━━━━━━━━━━━ Transformer ━━━━━━━━━━━━━━━┓
  transformer:
    heads:      4
    layers:     3
    ffn_dim:    8                                  # Feed-forward inner dim
    dropout:    0.2918083354050411
    activation: "mish"                               # gelu | relu | silu | mish

  # ┏━━━━━━━━━━━━━━ MLP Classifier ━━━━━━━━━━━━━━━┓
  classifier:
    mlp_hidden:   512
    mlp_dropout:  0.12831719171010209
    mlp_activation:   "relu"                          # gelu | relu | silu | mish
    mlp_pooling:      "attention"                     # attention | meanmax

# ┏━━━━━━━━━━ Training hyper-params (UP) ━━━━━━━━┓
train_up:
  # ┏━━━━━━━━━━ Optimizer ━━━━━━━━┓
  optimizer:      "adagrad"                            # adagrad | rmsprop | adam | adamw | adabelief | ranger
  lr:             9.235383791641308e-05
  weight_decay:   5.405750695992303e-05

  # ┏━━━━━━━━━━ Optimizer Parameters ━━━━━━━━┓
  eps:              1e-16                              # Only for adabelief
  betas:            [0.95, 0.98]                      # [beta1, beta2] Common for adam | adamw | adabelief | ranger
  lr_decay:         0.051591260301809654            # Only for Adagrad
  #rms_alpha:        0.9336763960402219                # Only for rmsprop
  #rms_momentum:     0.30881101362483226               # Only for rmsprop
  lookahead_k:      6                                  # Only for ranger (Lookahead)
  lookahead_alpha:  0.5                 # Only for ranger (Lookahead)
  weight_decouple:  True                              # Only for adabelief
  rectify:          False                               # Only for adabelief

  # ┏━━━━━━━━━━ Basic ━━━━━━━━┓
  batch_size:    64
  max_epochs:    50
  patience:      35                                   # Early-stopping
  bce_thr:       0.5                                  # BCE threshold
  fbeta:         0.9                                  # F-Beta Score (<1 + weight for precision, >1 for recall)

  # ┏━━━━━━━━━━ Learning Rate Scheduler ━━━━━━━━┓
  scheduler:                                          # Omit entire block → "none"
    sch_name: linear_plateau                                    # none | power | exponential | linear | cosine | plateau | linear_plateau | cosine_plateau
    warmup_epochs: 5
    plateau_patience: 19
    plateau_factor: 0.46818975818776315
    power_s: 0.23630352134198931                      # Power Scheduling
    power_c: 0.42006764977060695                      # Power Scheduling
    exp_s: 5                                          # Exponential Scheduling
    exp_factor: 0.1                                   # Exponential Scheduling

# ┏━━━━━━━━━━━━━━ Model – DN task ━━━━━━━━━━━━━━━┓
model_dn:
# ┏━━━━━━━━━━━━━━ CNN ━━━━━━━━━━━━━━━┓
  cnn_embed_dim: [256, 128]
  cnn_kernel:    [8, 8]
  cnn_stride:    [4, 4]
  p_pos_drop:    0.3442287792661535                # Positional-dropout

  # ┏━━━━━━━━━━━━━━ Transformer ━━━━━━━━━━━━━━━┓
  transformer:
    heads:      2
    layers:     3
    ffn_dim:    8                                  # Feed-forward inner dim
    dropout:    0.41113158694327917
    activation: "silu"                               # gelu | relu | silu | mish

  # ┏━━━━━━━━━━━━━━ MLP Classifier ━━━━━━━━━━━━━━━┓
  classifier:
    mlp_hidden:   512
    mlp_dropout:  0.05732176738929834
    mlp_activation:   "silu"                          # gelu | relu | silu | mish
    mlp_pooling:      "meanmax"                     # attention | meanmax

# ┏━━━━━━━━━━ Training hyper-params (DN) ━━━━━━━━┓
train_dn:
  # ┏━━━━━━━━━━ Optimizer ━━━━━━━━┓
  optimizer:      "adagrad"                            # adagrad | rmsprop | adam | adamw | adabelief | ranger
  lr:             1.1256334802872668e-05
  weight_decay:   0.0003861427434610027

  # ┏━━━━━━━━━━ Optimizer Parameters ━━━━━━━━┓
  eps:              1e-16                              # Only for adabelief
  betas:            [0.9, 0.98]                      # [beta1, beta2] Common for adam | adamw | adabelief | ranger
  lr_decay:         1.4376152378774033e-05          # Only for Adagrad
  #rms_alpha:        0.9336763960402219                # Only for rmsprop
  #rms_momentum:     0.30881101362483226               # Only for rmsprop
  lookahead_k:      6                                  # Only for ranger (Lookahead)
  lookahead_alpha:  0.5                 # Only for ranger (Lookahead)
  weight_decouple:  True                              # Only for adabelief
  rectify:          False                               # Only for adabelief

  # ┏━━━━━━━━━━ Basic ━━━━━━━━┓
  batch_size:    256
  max_epochs:    50
  patience:      35                                   # Early-stopping
  bce_thr:       0.5                                  # BCE threshold
  fbeta:         0.9                                  # F-Beta Score (<1 + weight for precision, >1 for recall)

  # ┏━━━━━━━━━━ Learning Rate Scheduler ━━━━━━━━┓
  scheduler:                                          # Omit entire block → "none"
    sch_name: cosine_plateau                                    # none | power | exponential | linear | cosine | plateau | linear_plateau | cosine_plateau
    warmup_epochs: 5
    plateau_patience: 20
    plateau_factor: 0.35715625826383646
    power_s: 0.23630352134198931                      # Power Scheduling
    power_c: 0.42006764977060695                      # Power Scheduling
    exp_s: 5                                          # Exponential Scheduling
    exp_factor: 0.1                                   # Exponential Scheduling