# ┏━━━━━━━━━━━━━━━ General paths ━━━━━━━━━━━━━━━━┓
paths:
  data_root: "Data"                                   # Where all raw providers live
  chronos_subdir: "Chronos"
  bolt_subdir: "Bolt"
  tirex_subdir: "Tirex"
  output_root: "Output"                               # Checkpoints / TensorBoard runs


# ┏━━━━━━━━━━ Which dataset to train on ━━━━━━━━━┓
dataset:
  source: "Chronos"                                    # Chronos | Bolt | Tirex
  type: "Crypto"                                       # Equities | Crypto
  symbol: "BTC"                                        # e.g. SPY or BTC


# ┏━━━━━━━━ Data-split & sequence shape ━━━━━━━━━┓
splits:
  train: 0.70                                          # Adds up to 1: train + val + test
  val: 0.15
  test: 0.15

sequence_length: 90                                    # 90 das (time-steps) as model context
column_features: ["close"]                             # Column Features such as "close", "open", etc...                                 
context_features: ["m1_prediction", "m1_dn", "m1_pred_proba_dn", "rel_interval_width",
  "forecast_slope", "bowley_skewness", "moors_kurtosis", "tail_asymmetry"] # Context Features such as "vix", "vcr", etc...                  

# ┏━━━━━━━━━━━━━━ Training Mode ━━━━━━━━━━━━━━━┓
training_mode:
  # ┏━━━━━━━━━━━━━━ Optuna ━━━━━━━━━━━━━━━┓
  cross_validation: false                              # Training with (true) or without (false) Cross-Validation (including Optuna)
  cross_val_props: 0.4                                 # Proportion for the Cross-Validation within the Training Split
  optuna_task: "UP"                                    # Only for Optuna Optimization

  loss_function: "cross_entropy"                       # bce | cross_entropy | focal
  focal_gamma: 3.3771842197375523
  focal_alpha: 0.7195401178935061
  num_classes: 2                                       # 1 (bce) | 2 (cross_entropy, focal)
  padding: true                                        # For 1D-CNN

# ┏━━━━━━━━━━━━━━ Model – UP task ━━━━━━━━━━━━━━━┓
model_up:
  # ┏━━━━━━━━━━━━━━ CNN ━━━━━━━━━━━━━━━┓
  cnn_blocks: 2
  cnn_embed_dim: [256, 64]
  cnn_kernel: [8, 8]
  cnn_stride: [1, 4]
  p_pos_drop: 0.43563321962431467                  # Positional-dropout

  # ┏━━━━━━━━━━━━━━ Transformer ━━━━━━━━━━━━━━━┓
  transformer:
    heads: 2
    layers: 4
    ffn_dim: 4                                     # Feed-forward inner dim
    dropout: 0.20972565347754824
    activation: "relu"                               # gelu | relu | silu | mish

  # ┏━━━━━━━━━━━━━━ MLP Classifier ━━━━━━━━━━━━━━━┓
  classifier:
    mlp_hidden: 512
    mlp_dropout: 0.0518048220566702
    mlp_activation: "relu"                            # gelu | relu | silu | mish
    mlp_pooling: "attention"                          # attention | meanmax

# ┏━━━━━━━━━━ Training hyper-params (UP) ━━━━━━━━┓
train_up:
  # ┏━━━━━━━━━━ Optimizer ━━━━━━━━┓
  optimizer: "adam"                                  # adagrad | rmsprop | adam | adamw | adabelief | ranger
  lr: 0.0018731981189624494
  weight_decay: 1.3329778287409796e-06

  # ┏━━━━━━━━━━ Optimizer Parameters ━━━━━━━━┓
  eps: '1e-16'                                         # Only for adabelief
  betas: [0.95, 0.98]                                 # [beta1, beta2] Common for adam | adamw | adabelief | ranger
  lr_decay: 5.771256799758024e-05                     # Only for Adagrad
  #rms_alpha:        0.9336763960402219                # Only for rmsprop
  #rms_momentum:     0.30881101362483226               # Only for rmsprop
  lookahead_k: 6                                       # Only for ranger (Lookahead)
  lookahead_alpha: 0.5                                # Only for ranger (Lookahead)
  # weight_decouple:  True                              # Only for adabelief
  # rectify:          False                               # Only for adabelief

  # ┏━━━━━━━━━━ Basic ━━━━━━━━┓
  batch_size: 32
  max_epochs: 50
  patience: 35                                        # Early-stopping
  bce_thr: 0.5                                        # BCE threshold
  fbeta: 0.9                                          # F-Beta Score (<1 + weight for precision, >1 for recall)

  # ┏━━━━━━━━━━ Learning Rate Scheduler ━━━━━━━━┓
  scheduler:                                          # Omit entire block → "none"
    sch_name: linear_plateau                                    # none | power | exponential | linear | cosine | plateau | linear_plateau | cosine_plateau
    warmup_epochs: 5
    plateau_patience: 18
    plateau_factor: 0.29893090323354105
    power_s: 0.23630352134198931                      # Power Scheduling
    power_c: 0.42006764977060695                      # Power Scheduling
    exp_s: 5                                          # Exponential Scheduling
    exp_factor: 0.1                                   # Exponential Scheduling

# ┏━━━━━━━━━━━━━━ Model – DN task ━━━━━━━━━━━━━━━┓
  loss_function: cross_entropy
  focal_alpha: 0.7195401178935061
model_dn:
  # ┏━━━━━━━━━━━━━━ CNN ━━━━━━━━━━━━━━━┓
  cnn_blocks: 2
  cnn_embed_dim: [256, 128]
  cnn_kernel: [4, 8]
  cnn_stride: [4, 2]
  p_pos_drop: 0.3429026660613288                   # Positional-dropout

  # ┏━━━━━━━━━━━━━━ Transformer ━━━━━━━━━━━━━━━┓
  transformer:
    heads: 4
    layers: 3
    ffn_dim: 8                                     # Feed-forward inner dim
    dropout: 0.3645140908637284
    activation: "silu"                               # gelu | relu | silu | mish

  # ┏━━━━━━━━━━━━━━ MLP Classifier ━━━━━━━━━━━━━━━┓
  classifier:
    mlp_hidden: 128
    mlp_dropout: 0.35903547684834725
    mlp_activation: "silu"                            # gelu | relu | silu | mish
    mlp_pooling: "attention"                          # attention | meanmax

# ┏━━━━━━━━━━ Training hyper-params (DN) ━━━━━━━━┓
train_dn:
  # ┏━━━━━━━━━━ Optimizer ━━━━━━━━┓
  optimizer: "adamw"                                 # adagrad | rmsprop | adam | adamw | adabelief | ranger
  lr: 0.0002606774929147222
  weight_decay: 3.979136956946215e-06

  # ┏━━━━━━━━━━ Optimizer Parameters ━━━━━━━━┓
  eps: 1e-16                                           # Only for adabelief
  betas: [0.95, 0.98]                                 # [beta1, beta2] Common for adam | adamw | adabelief | ranger
  lr_decay: 0.00015588083176258327                    # Only for Adagrad
  #rms_alpha:        0.9336763960402219                # Only for rmsprop
  #rms_momentum:     0.30881101362483226               # Only for rmsprop
  lookahead_k: 6                                       # Only for ranger (Lookahead)
  lookahead_alpha: 0.5                  # Only for ranger (Lookahead)
  weight_decouple: true                               # Only for adabelief
  rectify: false                                        # Only for adabelief

  # ┏━━━━━━━━━━ Basic ━━━━━━━━┓
  batch_size: 32
  max_epochs: 50
  patience: 35                                        # Early-stopping
  bce_thr: 0.5                                        # BCE threshold
  fbeta: 0.9                                          # F-Beta Score (<1 + weight for precision, >1 for recall)

  # ┏━━━━━━━━━━ Learning Rate Scheduler ━━━━━━━━┓
  scheduler:                                          # Omit entire block → "none"
    sch_name: linear_plateau                                    # none | power | exponential | linear | cosine | plateau | linear_plateau | cosine_plateau
    warmup_epochs: 5
    plateau_patience: 11
    plateau_factor: 0.31818009711567885
    power_s: 0.23630352134198931                      # Power Scheduling
    power_c: 0.42006764977060695                      # Power Scheduling
    exp_s: 5                                          # Exponential Scheduling
    exp_factor: 0.1                                   # Exponential Scheduling
